"use client"

import type { Metadata } from "next";
import "../styles/globals.css";
import { Provider } from "react-redux";
import store, { Persistor } from "../redux/store";
import { PersistGate } from "redux-persist/integration/react"; 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  <Provider store={store}>
   

         <html lang="en">
        
        <body>
 {/* <PersistGate loading={null} persistor={Persistor}> */}
          <div className="">{children}</div>

    {/* </PersistGate> */}
        </body>
    </html> 

  </Provider>
  

  );
}
